### TOPAS v3.2
export G4LEDATA=~/G4Data/G4EMLOW6.50
export G4NEUTRONHPDATA=~/G4Data/G4NDL4.5
export G4LEVELGAMMADATA=~/G4Data/PhotonEvaporation4.3.2
export G4RADIOACTIVEDATA=~/G4Data/RadioactiveDecay5.1.1
export G4SAIDXSDATA=~/G4Data/G4SAIDDATA1.1
export G4NEUTRONXSDATA=~/G4Data/G4NEUTRONXS1.4
export G4PIIDATA=~/G4Data/G4PII1.3
export G4REALSURFACEDATA=~/G4Data/RealSurface1.0
export G4ABLADATA=~/G4Data/G4ABLA3.0
export G4ENSDFSTATEDATA=~/G4Data/G4ENSDFSTATE2.1
export G4TENDLDATA=~/G4Data/G4TENDL1.3
#export G4VRMLFILE_VIEWER=view3dscene
export LD_LIBRARY_PATH=~/topas/libexternal/:$LD_LIBRARY_PATH
export PATH=~/topas:$PATH
